[basic]
task_mode = "batch_tasks"    # single_task or batch_tasks
global_reward = false        # with global reward
max_time_step = 25           # For all tasks, set the maximum step length

[model]
json_model_response = false      # Whether to require a model that serves restrict json output
json_models = ["gpt-4-turbo",
                   "gpt-4-turbo-2024-04-09",
                   "gpt-4-turbo-preview",
                   "gpt-4-0125-preview",
                   "gpt-4-1106-preview",
                   "gpt-3.5-turbo",
                   "gpt-3.5-turbo-0125",
                   "gpt-3.5-turbo-preview"]


[steps]
interaction_mode = true             #  Whether human control of task execution status is required
single_task_action_step = 10     
batch_tasks_max_action_step = 10
batch_tasks_condition_step_increase = 5

[files]
batch_tasks_file_path = "./data/example/test.json" # The input data path
ground_truth_file_path = "./data/human_labeled_reward_reference/GT_instructions_202404161811_for_all_data_0328.json"  # the ground_truth data path
out_file_path = "./batch_tasks_results/example"   # YOUR OUT FILE PATH 

[conditions]
URL = ["error"]